networks:
 default:
  driver: bridge 
  name: roboshop
 
services:
  mongodb:
    image: saivenkatuppu1/mongodb:v1
    container_name: mongodb
  catalogue:
    image: saivenkatuppu1/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  redis:
    image: redis:7.0
    container_name: redis
  user:
    image: saivenkatuppu1/user:v1
    container_name: user
    depends_on:
    - redis
    - mongodb
  cart:
    image: saivenkatuppu1/cart:v1
    container_name: cart
    depends_on:
    - catalogue
    - redis
  mysql:
    image: saivenkatuppu1/mysql:v1
    container_name: mysql
  shipping:
    image: saivenkatuppu1/shipping:v1
    container_name: shipping
    depends_on:
    - mysql
    - cart
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
     RABBITMQ_DEFAULT_USER: roboshop
     RABBITMQ_DEFAULT_PASS: roboshop123
    volumes:
    - rabbitmq:/var/lib/rabbitmq
  payment:
    image: saivenkatuppu1/payment:v1
    container_name: payment
    environment:
      CART_HOST: cart
      CART_PORT: 8080
      USER_HOST: user
      USER_PORT: 8080
      AMQP_HOST: rabbitmq
      AMQP_USER: roboshop
      AMQP_PASS: roboshop123
    depends_on:
    - rabbitmq
    - cart
    - user
  frontend:
    image: saivenkatuppu1/frontend:v1
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - shipping
    - payment 